# Generated by Django 5.1.1 on 2024-10-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_Email', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=3)),
                ('Year', models.CharField(max_length=10)),
                ('data', models.DateField()),
            ],
        ),
    ]
