# Generated by Django 5.1.1 on 2024-10-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_data_sign_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='Branch',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='College_Email',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
